source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'Example' do
    pod 'MSCollectionViewCalendarLayout', :path => '../'

    pod 'RestKit'
    pod 'CupertinoYankee'
    pod 'UIColor-HexString'
    pod 'Masonry'

end